name: vllm-test

on:
  push:
    tags:
      - ciflow/vllm/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  torch-build:
    name: ci-vllm-build
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-additional-packages: "vision audio"
      build-external-packages: "vllm"
      build-environment: linux-jammy-cuda12.8-py3.12-gcc11
      docker-image-name: ci-image:pytorch-linux-jammy-cuda12.8-cudnn9-py3.12-gcc11-vllm
      cuda-arch-list: '8.0 8.9 9.0'
      runner: linux.12xlarge.memory
      test-matrix: |
        { include: [
          { config: "vllm_basic_correctness_test", shard: 1, num_shards: 1, runner: "linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_basic_models_test", shard: 1, num_shards: 1, runner: "linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_regression_test", shard: 1, num_shards: 1, runner: "linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_entrypoints_test", shard: 1, num_shards: 1,runner: "linux.g6.4xlarge.experimental.nvidia.gpu" },
          { config: "vllm_basic_correctness_test", shard: 1, num_shards: 1, runner: "linux.aws.a100" },
          { config: "vllm_basic_models_test", shard: 1, num_shards: 1, runner: "linux.aws.a100" },
          { config: "vllm_regression_test", shard: 1, num_shards: 1, runner: "linux.aws.a100" },
          { config: "vllm_entrypoints_test", shard: 1, num_shards: 1, runner: "linux.aws.a100" },
        ]}
    secrets: inherit

  vllm-test:
      name: ci-vllm-test
      uses: ./.github/workflows/_linux-test.yml
      needs: [
        torch-build,
      ]
      with:
        build-environment: linux-jammy-cuda12.8-py3.12-gcc11
        docker-image: ${{ needs.torch-build.outputs.docker-image }}
        test-matrix: ${{ needs.torch-build.outputs.test-matrix }}
      secrets: inherit
